version: '3.8'

networks:
  backend:
    name: ${DOCKER_NET_NAME}
    driver: bridge

services:
  db_sever:
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    networks:
      - backend
    image: postgres:${DOCKER_DB_VERSION}
    expose:
      - 5432
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT}:5432 # Delete this line on production
    volumes:
      - .docker/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  web_server:
    container_name: ${DOCKER_NG_CONTAINER_NAME}
    networks:
      - backend
    build:
      context: .docker
      args:
        - php_version=${DOCKER_PHP_VERSION}
        - ng_root=${DOCKER_NG_ROOT}
        - time_zone=${APP_TIMEZONE}
    depends_on:
      - db_sever
    environment:
      #PHP
      PHP_VERSION: ${DOCKER_PHP_VERSION}
      PHP_TIMEZONE: ${DOCKER_PHP_TIMEZONE}

      # Nginx
      NG_HOST: ${DOCKER_NG_HOST}
      NG_PORT: ${DOCKER_NG_PORT}
      NG_EXTERNAL_PORT: ${DOCKER_NG_EXTERNAL_PORT}
      NG_ROOT: ${DOCKER_NG_ROOT}
    ports:
      - "${DOCKER_NG_EXTERNAL_PORT}:${DOCKER_NG_PORT}"
    volumes:
      - ./:/var/www/${DOCKER_NG_ROOT}/
    restart: always
    command: /bin/bash -c "/tmp/configure.sh && tail -f /dev/null"
